# Generated by Django 3.2.7 on 2022-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='sabudana-tikki'),
            preserve_default=False,
        ),
    ]
